# fly.toml app configuration file generated for laracamp on 2024-01-21T21:11:00+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "laracamp"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

  APP_URL = "https://laracamp.fly.dev"
  
  DB_CONNECTION = "pgsql"
  DB_HOST = "laracamp-postgresql.internal"
  DB_DATABASE= "laravel_laracamp" 
  DB_PORT = 5432
  
  GITHUB_CALLBACK_URL="https://laracamp.fly.dev/auth/github/callback"
  GOOGLE_CALLBACK_URL="https://laracamp.fly.dev/auth/google/callback"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
